/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package controle.de.estoque.sqlite;

import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitorbrito
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        painel = new javax.swing.JPanel();
        tabEstoque = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fieldFiltro = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaEstoque = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        radioAcre = new javax.swing.JRadioButton();
        radioDimi = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        spinnerQuant = new javax.swing.JSpinner();
        labelQuant = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelNomeProduto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelQuantProduto = new javax.swing.JLabel();
        btnBuscarProduto = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelIDProduto = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnNovoProduto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCadastro = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        fieldFiltroCadastro = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaHistorico = new javax.swing.JTable();

        radioGroup.add(radioAcre);
        radioGroup.add(radioDimi);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabEstoque.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabEstoqueStateChanged(evt);
            }
        });

        jLabel3.setText("Filtro:");

        fieldFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldFiltroKeyReleased(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        tabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                //        {null, null, null, null},
                //        {null, null, null, null},
                //        {null, null, null, null},
                //        {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Quantidade", "Descrição"
            }
        ));
        tabelaEstoque.setEnabled(false);
        jScrollPane3.setViewportView(tabelaEstoque);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 432, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(btnAtualizar)
                        .add(30, 30, 30)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fieldFiltro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAtualizar)
                    .add(jLabel3)
                    .add(fieldFiltro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 307, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabEstoque.addTab("Estoque Atual", jPanel1);

        radioAcre.setText("+ Acrescentar +");

        radioDimi.setText("- Diminuir -");
        radioDimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDimiActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        labelQuant.setText("Quantidade:");

        jLabel1.setText("Produto:");

        jLabel4.setText("Quant Atual:");

        btnBuscarProduto.setText("Buscar Produto");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data:");

        jLabel5.setText("ID Produto:");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(227, 227, 227)
                        .add(btnLimpar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel6)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(labelData))
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(radioAcre)
                                        .add(17, 17, 17)
                                        .add(radioDimi))
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel4)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(labelQuantProduto))
                                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(btnModificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jPanel3Layout.createSequentialGroup()
                                            .add(labelQuant)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                            .add(spinnerQuant, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .add(0, 102, Short.MAX_VALUE))
                            .add(jPanel3Layout.createSequentialGroup()
                                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel5)
                                        .add(13, 13, 13)
                                        .add(labelIDProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanel3Layout.createSequentialGroup()
                                        .add(jLabel1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(labelNomeProduto)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(btnBuscarProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(9, 9, 9)))))
                .add(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelIDProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5))
                        .add(13, 13, 13)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(labelNomeProduto)))
                    .add(btnBuscarProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(8, 8, 8)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(labelQuantProduto))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(labelData))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 45, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(radioAcre)
                    .add(radioDimi))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(spinnerQuant, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelQuant))
                .add(26, 26, 26)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnModificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnLimpar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22))
        );

        spinnerQuant.setModel(new SpinnerNumberModel(0, 0, 10000, 1));

        tabEstoque.addTab("Modificar Estoque", jPanel3);

        btnNovoProduto.setText("Novo Produto");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione um produto para edita-lo ou exclui-lo:");

        tabelaCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                //        {null, null, null, null},
                //        {null, null, null, null},
                //        {null, null, null, null},
                //        {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Descrição"
            }
        ));
        tabelaCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCadastro);

        jLabel7.setText("Filtro:");

        fieldFiltroCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldFiltroCadastroKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 385, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(btnNovoProduto)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel7)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(fieldFiltroCadastro))
                            .add(jLabel2))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnNovoProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(fieldFiltroCadastro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .add(12, 12, 12)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabEstoque.addTab("Cadastro", jPanel4);

        tabelaHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                //        {null, null, null, null},
                //        {null, null, null, null},
                //        {null, null, null, null},
                //        {null, null, null, null}
            },
            new String [] {
                "ID Produto", "Nome", "Quant Anterior", "Quant Alterada",
                "Quant Atual","Data"
            }
        ));
        jScrollPane2.setViewportView(tabelaHistorico);

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 346, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 9, Short.MAX_VALUE))
        );

        tabEstoque.addTab("Histórico", jPanel5);

        org.jdesktop.layout.GroupLayout painelLayout = new org.jdesktop.layout.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelLayout.createSequentialGroup()
                .add(tabEstoque, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 467, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabEstoque, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 401, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioDimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDimiActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        Integer quantidadeSpinner = Integer.parseInt(spinnerQuant.getValue().toString());

        if (labelIDProduto.getText() == "") {
            JOptionPane.showMessageDialog(null, "Busque um produto!");
        } else if (quantidadeSpinner == 0) {
            JOptionPane.showMessageDialog(null, "Selecione a quantidade desejada.");
        } else {

            Integer quantidadeAtual = Integer.parseInt(labelQuantProduto.getText().toString());
            Integer quantFinal = null;

            if (radioAcre.isSelected() && radioDimi.isSelected()) {
                System.out.println("ERROR! Os dois botões estão selecionados.");

            } else if (!radioAcre.isSelected() && radioDimi.isSelected()) {
                //Diminuir!
                if (quantidadeAtual >= quantidadeSpinner) {
                    //System.out.println("Diminuir " + quantidadeSpinner);

                    quantFinal = quantidadeAtual - quantidadeSpinner;

                    Conexao dbCon = new Conexao();
                    try {
                        dbCon.modificarEstoque(labelIDProduto.getText(), quantFinal);
                    } catch (SQLException | ClassNotFoundException ex) {
                        Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        dbCon.registrarHistorico(labelIDProduto.getText(), labelNomeProduto.getText(), quantidadeAtual.toString(), quantidadeSpinner.toString(), quantFinal.toString());
                    } catch (SQLException | ClassNotFoundException ex) {
                        Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    //String idProduto, String nomeProduto, String quantAnterior, String quantAlterada, String quantAtual

                    labelIDProduto.setText("");
                    labelNomeProduto.setText("");
                    labelQuantProduto.setText("");
                    spinnerQuant.setValue(0);
                    tabEstoque.setSelectedIndex(0);

                } else {
                    JOptionPane.showMessageDialog(null, "Quantidade em Estoque insuficiente!");
                }

            } else if (radioAcre.isSelected() && !radioDimi.isSelected()) {
                //Acrescentar!
                quantFinal = quantidadeAtual + quantidadeSpinner;

                Conexao dbCon = new Conexao();
                try {
                    dbCon.modificarEstoque(labelIDProduto.getText(), quantFinal);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    dbCon.registrarHistorico(labelIDProduto.getText(), labelNomeProduto.getText(), quantidadeAtual.toString(), quantidadeSpinner.toString(), quantFinal.toString());
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                }

                labelIDProduto.setText("");
                labelNomeProduto.setText("");
                labelQuantProduto.setText("");
                spinnerQuant.setValue(0);
                tabEstoque.setSelectedIndex(0);

            } else if (!radioAcre.isSelected() && !radioDimi.isSelected()) {
                //System.out.println("Nenhum Selecionado!");
                JOptionPane.showMessageDialog(null, "Selecione a operação desejada!");
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        labelIDProduto.setText("");
        labelNomeProduto.setText("");
        labelQuantProduto.setText("");
        spinnerQuant.setValue(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:

        Date dataHoje = new Date(System.currentTimeMillis());
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String oi = (formatarDate.format(dataHoje)).toString();
        System.out.println(oi);

        Conexao dbCon = new Conexao();
        try {
            dbCon.getTabelaEstoque();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        // TODO add your handling code here:
        Cadastro janelaCadastro = new Cadastro();
        janelaCadastro.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        janelaCadastro.setVisible(true);
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        // TODO add your handling code here:
        ListaProdutos listaProdutos = new ListaProdutos();
        listaProdutos.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        Conexao dbCon = new Conexao();
        try {
            dbCon.getListaProdutos();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }

        listaProdutos.setVisible(true);
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void tabEstoqueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabEstoqueStateChanged
        // TODO add your handling code here:
        int tabIndex = tabEstoque.getSelectedIndex();

        Conexao dbCon = new Conexao();

        //Método usado para atualizar as tabelas, quando o usuario muda de aba.
        switch (tabIndex) {
            case 0:
                try {
                    dbCon.getTabelaEstoque();
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case 1:
                Date dataHoje = new Date(System.currentTimeMillis());
                SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");
                Janela.labelData.setText(formatarDate.format(dataHoje));
                break;
            case 2:
                try {
                    dbCon.getTabelaCadastro();
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case 3:
                try {
                    dbCon.getTabelaHistorico();
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }

    }//GEN-LAST:event_tabEstoqueStateChanged

    private void fieldFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldFiltroKeyReleased
        // TODO add your handling code here:
        Conexao dbCon = new Conexao();
        try {
            dbCon.filtrarTabelaEstoque(fieldFiltro.getText());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fieldFiltroKeyReleased

    private void tabelaCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCadastroMouseClicked
        // TODO add your handling code here:
        EditarProduto editarProduto = new EditarProduto();
        editarProduto.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        int row = tabelaCadastro.getSelectedRow();
        String id = (String) tabelaCadastro.getValueAt(row, 0);

        Conexao dbCon = new Conexao();
        try {
            dbCon.getProdutoAtualizar(id);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ListaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }

        editarProduto.setVisible(true);
    }//GEN-LAST:event_tabelaCadastroMouseClicked

    private void fieldFiltroCadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldFiltroCadastroKeyReleased
        // TODO add your handling code here:
        Conexao dbCon = new Conexao();
        try {
            dbCon.filtrarTabelaCadastro(fieldFiltroCadastro.getText());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ListaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fieldFiltroCadastroKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNovoProduto;
    public static javax.swing.JTextField fieldFiltro;
    public static javax.swing.JTextField fieldFiltroCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JLabel labelData;
    public static javax.swing.JLabel labelIDProduto;
    public static javax.swing.JLabel labelNomeProduto;
    private javax.swing.JLabel labelQuant;
    public static javax.swing.JLabel labelQuantProduto;
    private javax.swing.JPanel painel;
    private javax.swing.JRadioButton radioAcre;
    private javax.swing.JRadioButton radioDimi;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JSpinner spinnerQuant;
    private javax.swing.JTabbedPane tabEstoque;
    public static javax.swing.JTable tabelaCadastro;
    public static javax.swing.JTable tabelaEstoque;
    public static javax.swing.JTable tabelaHistorico;
    // End of variables declaration//GEN-END:variables
}
